spring.application.name=my-market-app

spring.r2dbc.url=r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.h2.console.enabled=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:import.sql

spring.data.redis.host = 127.0.0.1
spring.data.redis.port = 6379
spring.data.redis.timeout=2000ms
spring.data.web.pageable.serialization-mode=via-dto
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

payment.service.url=http://127.0.0.1:8081