DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    count INTEGER NOT NULL,
    item_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE items (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   price BIGINT,
   description VARCHAR(255),
   img_path VARCHAR(255),
   title VARCHAR(255),
   PRIMARY KEY (id)
);

CREATE TABLE order_items (
    quantity INTEGER NOT NULL,
    item_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    price BIGINT,
    PRIMARY KEY (item_id, order_id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total_sum BIGINT,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS cart_items
    ADD CONSTRAINT FK_cart_items_item
    FOREIGN KEY (item_id)
    REFERENCES items;

ALTER TABLE IF EXISTS order_items
    ADD CONSTRAINT FK_order_items_item
    FOREIGN KEY (item_id)
    REFERENCES items;

ALTER TABLE IF EXISTS order_items
    ADD CONSTRAINT FK_order_items_order
    FOREIGN KEY (order_id)
    REFERENCES orders;