<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.mnuykin</groupId>
        <artifactId>my-market-app</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>payment-openapi</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.22</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.22.2</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.11</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.25.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/payment-openapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>org.mnuykin.server.api</apiPackage>
                            <modelPackage>org.mnuykin.server.domain</modelPackage>
                            <configOptions>
                                <reactive>true</reactive>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useTags>true</useTags>
                                <generateApiTests>false</generateApiTests>
                                <generateModelTests>false</generateModelTests>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-payment-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/payment-openapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>org.mnuykin.client.api</apiPackage>
                            <modelPackage>org.mnuykin.client.domain</modelPackage>
                            <invokerPackage>org.mnuykin.client.client</invokerPackage>
                            <configOptions>
                                <reactive>true</reactive>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-http-interface</library>
                                <useTags>true</useTags>
                                <generateApiTests>false</generateApiTests>
                                <generateModelTests>false</generateModelTests>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>